python main_run_sd_0215.py --save_path ./results/260220_meeting/15-optim --out_mode bg+inst_bg+inst --negative_prompt "ugly, blur, low quality, poor quality, deformed" --model_id 1 --dataset_yaml ./test_yaml/our_testcase.yaml --bce_mode --bce_grad 1 --bce_optim 1 --bce_neg 10 --mul_region_mode --mul_grad 10 --mul_optim 30 --gaus 0 --max_iter 15 &
python main_run_sd_0215.py --save_path ./results/260220_meeting/15-optim --out_mode bg+inst_bg+inst --negative_prompt "ugly, blur, low quality, poor quality, deformed" --model_id 1 --dataset_yaml ./test_yaml/our_testcase.yaml --bce_mode --bce_grad 1 --bce_optim 1 --bce_neg 20 --mul_region_mode --mul_grad 10 --mul_optim 30 --gaus 0 --max_iter 15 &
wait
python main_run_sd_0215.py --save_path ./results/260220_meeting/15-optim --out_mode bg+inst_bg+inst --negative_prompt "ugly, blur, low quality, poor quality, deformed" --model_id 1 --dataset_yaml ./test_yaml/our_testcase.yaml --bce_mode --bce_grad 1 --bce_optim 1 --bce_neg 10 --mul_region_mode --mul_grad 20 --mul_optim 20 --gaus 0 --max_iter 15 &
python main_run_sd_0215.py --save_path ./results/260220_meeting/15-optim --out_mode bg+inst_bg+inst --negative_prompt "ugly, blur, low quality, poor quality, deformed" --model_id 1 --dataset_yaml ./test_yaml/our_testcase.yaml --bce_mode --bce_grad 1 --bce_optim 1 --bce_neg 10 --mul_region_mode --mul_grad 25 --mul_optim 25 --gaus 0 --max_iter 15 &
wait
python main_run_sd_0215.py --save_path ./results/260220_meeting/15-optim --out_mode bg+inst_bg+inst --negative_prompt "ugly, blur, low quality, poor quality, deformed" --model_id 1 --dataset_yaml ./test_yaml/our_testcase.yaml --bce_mode --bce_grad 1 --bce_optim 1 --bce_neg 10 --mul_region_mode --mul_grad 10 --mul_optim 20 --gaus 0 --max_iter 15 &
python main_run_sd_0215.py --save_path ./results/260220_meeting/15-optim --out_mode bg+inst_bg+inst --negative_prompt "ugly, blur, low quality, poor quality, deformed" --model_id 1 --dataset_yaml ./test_yaml/our_testcase.yaml --bce_mode --bce_grad 1 --bce_optim 1 --bce_neg 10 --mul_region_mode --mul_grad 10 --mul_optim 25 --gaus 0 --max_iter 15 &
wait
python main_run_sd_0215.py --save_path ./results/260220_meeting/15-optim --out_mode bg+inst_bg+inst --negative_prompt "ugly, blur, low quality, poor quality, deformed" --model_id 2 --dataset_yaml ./test_yaml/our_testcase.yaml --bce_mode --bce_grad 1 --bce_optim 1 --bce_neg 50 --mul_region_mode --mul_grad 30 --mul_optim 30 --gaus 0 --max_iter 15 &
python main_run_sd_0215.py --save_path ./results/260220_meeting/15-optim --out_mode bg+inst_bg+inst --negative_prompt "ugly, blur, low quality, poor quality, deformed" --model_id 2 --dataset_yaml ./test_yaml/our_testcase.yaml --bce_mode --bce_grad 1 --bce_optim 1 --bce_neg 10 --mul_region_mode --mul_grad 30 --mul_optim 33 --gaus 0 --max_iter 15 &
wait
python main_run_sd_0215.py --save_path ./results/260220_meeting/15-optim --out_mode bg+inst_bg+inst --negative_prompt "ugly, blur, low quality, poor quality, deformed" --model_id 1 --dataset_yaml ./test_yaml/our_testcase.yaml --bce_mode --bce_grad 1 --bce_optim 1 --bce_neg 40 --mul_region_mode --mul_grad 30 --mul_optim 30 --gaus 0 --max_iter 15 &
python main_run_sd_0215.py --save_path ./results/260220_meeting/15-optim --out_mode bg+inst_bg+inst --negative_prompt "ugly, blur, low quality, poor quality, deformed" --model_id 1 --dataset_yaml ./test_yaml/our_testcase.yaml --bce_mode --bce_grad 1 --bce_optim 10 --bce_neg 10 --mul_region_mode --mul_grad 30 --mul_optim 30 --gaus 0 --max_iter 15 &
wait
python main_run_sd_0215.py --save_path ./results/260220_meeting/15-optim --out_mode bg+inst_bg+inst --negative_prompt "ugly, blur, low quality, poor quality, deformed" --model_id 1 --dataset_yaml ./test_yaml/our_testcase.yaml --bce_mode --bce_grad 1 --bce_optim 10 --bce_neg 50 --mul_region_mode --mul_grad 30 --mul_optim 30 --gaus 0 --max_iter 15 &
python main_run_sd_0215.py --save_path ./results/260220_meeting/15-optim --out_mode bg+inst_bg+inst --negative_prompt "ugly, blur, low quality, poor quality, deformed" --model_id 1 --dataset_yaml ./test_yaml/our_testcase.yaml --bce_mode --bce_grad 10 --bce_optim 10 --bce_neg 50 --mul_region_mode --mul_grad 30 --mul_optim 30 --gaus 0 --max_iter 15 &
wait
# python main_run_sd_0215.py --save_path ./results/260220_meeting/15-optim --out_mode bg+inst_bg+inst --negative_prompt "ugly, blur, low quality, poor quality, deformed" --model_id 1 --dataset_yaml ./test_yaml/our_testcase.yaml --bce_mode --bce_grad 1 --bce_optim 1 --bce_neg 10 --mul_region_mode --mul_grad 10 --mul_optim 20 --gaus 0 --max_iter 15 &
# python main_run_sd_0215.py --save_path ./results/260220_meeting/15-optim --out_mode bg+inst_bg+inst --negative_prompt "ugly, blur, low quality, poor quality, deformed" --model_id 1 --dataset_yaml ./test_yaml/our_testcase.yaml --bce_mode --bce_grad 1 --bce_optim 1 --bce_neg 10 --mul_region_mode --mul_grad 10 --mul_optim 25 --gaus 0 --max_iter 15 &
# wait